export const JOB_POSTED_START = 'JOB_POSTED_START';
export const JOB_POSTED_SUCCESS = 'JOB_POSTED_SUCCESS';
export const JOB_POSTED_FAILURE = 'JOB_POSTED_FAILURE';

export const JOB_BID_START = 'JOB_BID_START';
export const JOB_BID_SUCCESS = 'JOB_BID_SUCCESS';
export const JOB_BID_FAILURE = 'JOB_BID_FAILURE';

export const JOB_MATCHED_START = 'JOB_MATCHED_START';
export const JOB_MATCHED_SUCCESS = 'JOB_MATCHED_SUCCESS';
export const JOB_MATCHED_FAILURE = 'JOB_MATCHED_FAILURE';

export const SERVICE_PROVIDER_START = 'SERVICE_PROVIDER_START';
export const SERVICE_PROVIDER_SUCCESS = 'SERVICE_PROVIDER_SUCCESS';
export const SERVICE_PROVIDER_FAILURE = 'SERVICE_PROVIDER_FAILURE';

export const JOB_DETAILS_START = 'JOB_DETAILS_START';
export const JOB_DETAILS_SUCCESS = 'JOB_DETAILS_SUCCESS';
export const JOB_DETAILS_FAILURE = 'JOB_DETAILS_FAILURE';

export const ACCEPT_REQUEST_START = 'ACCEPT_REQUEST_START';
export const ACCEPT_REQUEST_SUCCESS = 'ACCEPT_REQUEST_SUCCESS';
export const ACCEPT_REQUEST_FAILURE = 'ACCEPT_REQUEST_FAILURE';

export const RATE_START = 'RATE_START';
export const RATE_SUCCESS = 'RATE_SUCCESS';
export const RATE_FAILURE = 'RATE_FAILURE';