export const CURRENT_LOCATION = 'CURRENT_LOCATION';

export const GET_CATEGORY_LIST_START = 'GET_CATEGORY_LIST_START';
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS';
export const GET_CATEGORY_LIST_FAILURE = 'GET_CATEGORY_LIST_FAILURE';

export const REFRESH_CATEGORY_LIST_START = 'REFRESH_CATEGORY_LIST_START';

export const GET_ALL_SERVICES_LIST_START = 'GET_ALL_SERVICES_LIST_START';
export const GET_ALL_SERVICES_LIST_SUCCESS = 'GET_ALL_SERVICES_LIST_SUCCESS';
export const GET_ALL_SERVICES_LIST_FAILURE = 'GET_ALL_SERVICES_LIST_FAILURE';

export const REFRESH_ALL_SERVICES_LIST_START = 'REFRESH_ALL_SERVICES_LIST_START';

export const GET_PROVIDER_LIST_START = 'GET_PROVIDER_LIST_START';
export const GET_PROVIDER_LIST_SUCCESS = 'GET_PROVIDER_LIST_SUCCESS';
export const GET_PROVIDER_LIST_FAILURE = 'GET_PROVIDER_LIST_FAILURE';

export const REFRESH_PROVIDER_LIST_START = 'REFRESH_PROVIDER_LIST_START';

export const POST_JOB_START = 'POST_JOB_START';
export const POST_JOB_SUCCESS = 'POST_JOB_SUCCESS';
export const POST_JOB_FAILURE = 'POST_JOB_FAILURE';

export const ADMIN_DATA_START = 'ADMIN_DATA_START';
export const ADMIN_DATA_SUCCESS = 'ADMIN_DATA_SUCCESS';
export const ADMIN_DATA_FAILURE = 'ADMIN_DATA_FAILURE';

export const GET_REGIONS_START = 'GET_REGIONS_START';
export const GET_REGIONS_SUCCESS = 'GET_REGIONS_SUCCESS';
export const GET_REGIONS_FAILURE = 'GET_REGIONS_FAILURE';